### ISSUE TITLE
Set Shell script automation

### ISSUE THREAD

**Issue by JslYoon** [BU-DiSC/bliss_benchmark#21]
Currently, steps in testing and evaluating each data structure need to be done manually.
Potentially adding a Shell script file to automate the process of 
data generation (BoDS), execution (BLISS, different workloads), and heatmap generation 
would be helpful.

**Comment by ramananeesh** [comment]
@JslYoon these are independent processes. Data generation happens once and can be re-used for multiple data structures during execution, as the workloads are managed through the driver code. We currently have a script for executing a workload configuration for a list of data structures, which writes the results to a sqlite database. Heatmap generation is also done on demand. 

I don't know if a single script to do all these three will ever be used in our current framework. Please let us know if you have a definitive reason to do so. Otherwise, we can close this issue.

**Comment by JslYoon** [comment]
Yes, that's fair. I asked because of a potential future add-on, and I understand it wouldn't be really necessary. I can close this issue. Thank you for the comment!
